spring.application.name=leetcodehabitfinal

spring.datasource.url=jdbc:mysql://localhost:3306/dsa_habit_tracker
spring.datasource.username=root
spring.datasource.password=JanviDinesh12345
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
